name: MoneyMakerAIDevContainer

on:
  push:
    tags:
      - "*.*.*"
    paths:
      - ".github/workflows/devcontainer.yml"
      - "Dockerfile.Basic"
      - "Dockerfile.Baseimage"
      - "requirements.txt"

env:
  REGISTRY: ghcr.io
  IMAGE_TAG_BASEIMAGE: moneymaker-baseimage
  IMAGE_TAG_DEVCONTAINER: moneymaker-ai-devcontainer

jobs:
  base_image:
    uses: ./.github/workflows/build_and_push.yaml
    with:
      registry: ghcr.io
      dockerfile_path: ./Dockerfile.Baseimage
      base_image: python:3.8.10
      image_name: moneymaker-baseimage
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}

  dev_container:
    uses: ./.github/workflows/build_and_push.yaml
    needs: base_image
    with:
      registry: ghcr.io
      dockerfile_path: ./Dockerfile.Basic
      base_image: ${{ needs.base_image.outputs.imagerepository }}
      image_name: moneymaker-ai-devcontainer
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
