name: MoneyMakerAIDevContainerGPU

on:
  push:
    tags:
      - "*.*.*"
    paths:
      - ".github/workflows/devcontainer-gpu.yml"
      - "Dockerfile.GPU"
      - "requirements.txt"

jobs:
  devcontainer_gpu:
    uses: ./.github/workflows/build_and_push.yaml
    with:
      registry: ghcr.io
      dockerfile_path: ./Dockerfile.GPU
      base_image: tensorflow/tensorflow:latest-gpu
      image_name: moneymaker-ai-devcontainer-gpu
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
